### ISSUE TITLE
cng.ExtractHKDF panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by ksbytov** [microsoft/go-crypto-winnative#70]
Hello, 
I have one Windows 10 (Version 10.0.17134 Build 17134) VM on which cng.ExtractHKDF panics.

I have this happening in the real app but it is also reproducible with unit test.
(tests.exe is built like this: GOOS=windows GOARCH=amd64 ~/go/go1.22.2/bin/go test hkdf_test.go -c -o tests.exe)
```
C:\>tests.exe
--- FAIL: TestHKDF (0.00s)
panic: runtime error: slice bounds out of range [185273103:22] [recovered]
        panic: runtime error: slice bounds out of range [185273103:22]

goroutine 6 [running]:
testing.tRunner.func1.2({0x4ceec0, 0xc000014108})
        /Users/kirillsbytov/go/go1.22.2/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        /Users/kirillsbytov/go/go1.22.2/src/testing/testing.go:1634 +0x377
panic({0x4ceec0?, 0xc000014108?})
        /Users/kirillsbytov/go/go1.22.2/src/runtime/panic.go:770 +0x132
github.com/microsoft/go-crypto-winnative/cng.ExtractHKDF(0x0?, {0x5d1c30?, 0x4638c0?, 0x5c7610?}, {0x5d17d8?, 0x4c7fc0?, 0x1?})
        /Users/kirillsbytov/go/src/github.com/microsoft/go-crypto-winnative/cng/hkdf.go:166 +0x1a5
command-line-arguments_test.TestHKDF(0xc00010e4e0)
        /Users/kirillsbytov/go/src/github.com/microsoft/go-crypto-winnative/cng/hkdf_test.go:315 +0x11c
testing.tRunner(0xc00010e4e0, 0x4ea848)
        /Users/kirillsbytov/go/go1.22.2/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        /Users/kirillsbytov/go/go1.22.2/src/testing/testing.go:1742 +0x390
```
when I printed the key blob from ExtractHKDF
```
func ExtractHKDF(h func() hash.Hash, secret, salt []byte) ([]byte, error) {
...
	// KEY_DATA_BLOB_VERSION1 format is:
	// cbHash uint32 // Big-endian
	// hashName [cbHash]byte
	// key []byte // Rest of the blob
	fmt.Fprintf(os.Stderr, "KEY_DATA_BLOB_VERSION1 blob: %v", blob)
	if len(blob) < 4 {
		return nil, errors.New("cng: exported key is corrupted")
	}
...
}
```
it resulted in 
KEY_DATA_BLOB_VERSION1 blob: [13 198 121 161 249 46 102 90 112 4 39 122 177 40 154 234 181 153 145 230 25 83 8 242 53 150 167 218 158 198 164 108]
panic: runtime error: slice bounds out of range [231111077:32]

This doesn't happen on another Windows 10 VM in my test environment but on this one it is stable reproducible.
Thank you in advance for any feedback on this.

**Comment by karianna** [comment]
@ksbytov Are you able to try with MSFT Go [1.22.8-1](https://github.com/microsoft/go/releases/tag/v1.22.8-1)?

**Comment by ksbytov** [comment]
@karianna it is still reproducible 
```
C:\>test-cng.exe
panic: runtime error: slice bounds out of range [2680727777:32]

goroutine 9 [running]:
vendor/github.com/microsoft/go-crypto-winnative/cng.ExtractHKDF(0x556c7a?, {0xc000012600?, 0xc0001478a0?, 0xc0000126a0?}, {0xc0000126e0?, 0xc000147960?, 0x47edb2?})
        /usr/local/go/src/vendor/github.com/microsoft/go-crypto-winnative/cng/hkdf.go:170 +0x1a5
crypto/internal/backend.ExtractHKDF(...)
        /usr/local/go/src/crypto/internal/backend/cng_windows.go:211
crypto/tls.(*cipherSuiteTLS13).extract(0x758e00, {0xc000012600?, 0x1c?, 0x1c?}, {0xc0000126e0, 0x20, 0x20})
        /usr/local/go/src/crypto/tls/key_schedule.go:93 +0x165
crypto/tls.(*clientHandshakeStateTLS13).establishHandshakeKeys(0xc000147bd0)
        /usr/local/go/src/crypto/tls/handshake_client_tls13.go:387 +0x138
crypto/tls.(*clientHandshakeStateTLS13).handshake(0xc000147bd0)
        /usr/local/go/src/crypto/tls/handshake_client_tls13.go:86 +0x274
crypto/tls.(*Conn).clientHandshake(0xc000004708, {0x5d03b8, 0xc000056190})
        /usr/local/go/src/crypto/tls/handshake_client.go:265 +0x594
crypto/tls.(*Conn).handshakeContext(0xc000004708, {0x5d0348, 0x7e9b00})
        /usr/local/go/src/crypto/tls/conn.go:1553 +0x3cb
crypto/tls.(*Conn).HandshakeContext(...)
        /usr/local/go/src/crypto/tls/conn.go:1493
net/http.(*persistConn).addTLS.func2()
        /usr/local/go/src/net/http/transport.go:1573 +0x6e
created by net/http.(*persistConn).addTLS in goroutine 6
        /usr/local/go/src/net/http/transport.go:1569 +0x309
```
the application code is just 
```
package main

import (
	"fmt"
	"net/http"
)

func main() {
	client := http.Client{}
	fmt.Println(client.Get("https://www.google.com"))
}
```
built like this:
```
docker run -v /Users/kirillsbytov/GolandProjects/test-cng:/go/test-cng  mcr.microsoft.com/oss/go/microsoft/golang:1.22.8-1-fips-cbl-mariner2.0 bash -c 'cd /go/test-cng && GOOS=windows GOARCH=amd64 go build'
```

**Comment by qmuntal** [comment]
> This doesn't happen on another Windows 10 VM in my test environment but on this one it is stable reproducible.

Which version is this other Windows 10 VM that doesn't exhibit the error?

**Comment by ksbytov** [comment]
@qmuntal it is Microsoft Windows [Version 10.0.19045.4291]
