### ISSUE TITLE
cng.aesGCM.Seal panic: winapi error #-1073741811

### ISSUE THREAD

**Issue by SkyBlueBluee** [microsoft/go-crypto-winnative#77]
Hi! 

I have a problem where my application is panicking when calling Seal. This only happens on 32 bit Windows environments according to my QA. 

```
panic: winapi error #-1073741811

goroutine 1 [running]:
vendor/github.com/microsoft/go-crypto-winnative/cng.(*aesGCM).Seal(0xa4298c0, {0x0, 0x0, 0x0}, {0xa5513b0, 0xc, 0xc}, {0xa429860, 0x20, 0x20}, ...)
	/usr/local/go/src/vendor/github.com/microsoft/go-crypto-winnative/cng/aes.go:327 +0x54f
```

I tried reproducing by building and running unit tests on 32 bit windows 10:

Built using 
`go test aes_test.go cng_test.go -c -o test.exe` where the go version is `go version go1.22.2 windows/386` and `GOARCH=386`

```
--- FAIL: TestSealAndOpen (0.00s)
panic: winapi error #-1073741811 [recovered]
        panic: winapi error #-1073741811

goroutine 7 [running]:
testing.tRunner.func1.2({0x8705e0, 0x180a1b4})
        C:/Program Files/Go/src/testing/testing.go:1631 +0x2a1
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1634 +0x432
panic({0x8705e0, 0x180a1b4})
        C:/Program Files/Go/src/runtime/panic.go:770 +0xf6
github.com/microsoft/go-crypto-winnative/cng.(*aesGCM).Seal(0x1814340, {0x0, 0x0, 0x0}, {0x180a1a0, 0xc, 0xc}, {0x180a1a0, 0x3, 0x3}, ...)
        C:/Program Files/git.acronis.com/microsoft-go-crypto-winnative/cng/aes.go:331 +0x512
command-line-arguments_test.TestSealAndOpen(0x1900208)
        C:/Program Files/git.acronis.com/microsoft-go-crypto-winnative/cng/aes_test.go:74 +0x209
testing.tRunner(0x1900208, 0x88e86c)
        C:/Program Files/Go/src/testing/testing.go:1689 +0x123
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1742 +0x3b7
```
I also printed out the function inputs: 
```
	info := bcrypt.NewAUTHENTICATED_CIPHER_MODE_INFO(nonce, additionalData, out[len(out)-gcmTagSize:])
	var encSize uint32
	fmt.Fprintf(os.Stderr, "plaintext: %v, info: %v, info_ptr: %v, out: %v, encSize: %v, &encSize: %v\n", plaintext, *info, unsafe.Pointer(info), out, encSize, &encSize)
	err := bcrypt.Encrypt(g.kh, plaintext, unsafe.Pointer(info), nil, out, &encSize, 0)
	if err != nil {
		panic(err)
	}
	if int(encSize) != len(plaintext) {
		panic("crypto/aes: plaintext not fully encrypted")
	}

plaintext: [1 2 3], info: {56 1 0x9c1a190 12 0x9c1a1a0 3 0x9c16243 16 <nil> 0 0 0 0}, info_ptr: 0x9c300c0, out: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], encSize: 0, &encSize: 0x9c1a1a4
```

Windows version is: Windows 10 - 19045.5131

Is this a known issue or some misconfiguration/error on my end?

**Comment by SkyBlueBluee** [comment]
I tested and built using `GOARCH=amd64` and it was successful. Looks like issue might have to do with the padding because output of the parameters passed to  `Encrypt` look like: 
```
plaintext: [1 2 3], info: {88 1 0xc00001e220 12 0xc00001e21b 3 0xc000018243 16 <nil> 0 0 0 0}, info_ptr: 0xc000122060, out: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0], encSize: 0, &encSize: 0xc00001e230
```

**Comment by qmuntal** [comment]
Thanks for reporting this issue. I can reproduce it locally by running `go test -run TestSealAndOpen ./...` with `GOARCH=386`. I is indeed an issue with the `AUTHENTICATED_CIPHER_MODE_INFO` padding, Go's layout doesn't match Win32 layout on 32 bit.

Having said this, there are many other failing test on 32 bit Windows, so I'm inclined to not fix this particular issue and just state that we don't support 32 bit Windows.

I'm curious, why do you use 32 bit Windows @SkyBlueBluee?

**Comment by SkyBlueBluee** [comment]
It was a requirement for one of our features. Will tell my team that we will just not support 32 bit Windows. Thanks @qmuntal !
